-- +goose Up
-- +goose StatementBegin
create extension if not exists citext;
CREATE TABLE clients (
  id int primary key generated by default as identity,
  name text not null,
  email citext not null unique
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE clients;
-- +goose StatementEnd
